kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# ─────────────────────────────────────────────
# control‑plane ─ 无特殊标签，主要跑系统组件
# ─────────────────────────────────────────────
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # Kafka 外部访问示例
        hostPort: 30000
      - containerPort: 30001  # MinIO 控制台
        hostPort: 30001
      - containerPort: 30002  # Spark Driver UI
        hostPort: 30002
  # ─────────────────────────────────────────────
  # Kafka 专属节点池 (2)
  #   label: tier=kafka
  #   taint: tier=kafka:NoSchedule
  # ─────────────────────────────────────────────
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: kafka-1
          kubeletExtraArgs:
            node-labels: "tier=kafka"
            register-with-taints: "tier=kafka:NoSchedule"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: kafka-2
          kubeletExtraArgs:
            node-labels: "tier=kafka"
            register-with-taints: "tier=kafka:NoSchedule"
  # ─────────────────────────────────────────────
  # Spark 计算节点池 (2)
  #   label: tier=compute
  #   无 taint，允许其他轻量任务共用（如监控 sidecar）
  # ─────────────────────────────────────────────
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: compute-1
          kubeletExtraArgs:
            node-labels: "tier=compute"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: compute-2
          kubeletExtraArgs:
            node-labels: "tier=compute"
  # ─────────────────────────────────────────────
  # MinIO 持久化节点池 (2)
  #   label: tier=storage
  #   taint: tier=storage:NoSchedule
  # ─────────────────────────────────────────────
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: storage-1
          kubeletExtraArgs:
            node-labels: "tier=storage"
            register-with-taints: "tier=storage:NoSchedule"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: storage-2
          kubeletExtraArgs:
            node-labels: "tier=storage"
            register-with-taints: "tier=storage:NoSchedule"
networking:
  disableDefaultCNI: false
  kubeProxyMode: "iptables"