# Directory: k8s/services/spark-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-service
spec:
  selector:
    app: spark-driver
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
  type: ClusterIP
