# Directory: k8s/base/spark-executor-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-executor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-executor
  template:
    metadata:
      labels:
        app: spark-executor
    spec:
      containers:
        - name: spark-executor
          image: spark-custom:latest
          ports:
            - containerPort: 4040
          env:
            - name: SPARK_EXECUTOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name